const city = [
  {
    id: 1,
    name: "Abra",
    cities: [
      "Bangued",
      "Boliney",
      "Bucay",
      "Bucloc",
      "Daguioman",
      "Danglas",
      "Dolores",
      "La Paz",
      "Lacub",
      "Lagangilang",
      "Lagayan",
      "Langiden",
      "Licuan-Baay",
      "Luba",
      "Malibcong",
      "Manabo",
      "Peñarrubia",
      "Pidigan",
      "Pilar",
      "Sallapadan",
      "San Isidro",
      "San Juan",
      "San Quintin",
      "Tayum",
      "Tineg",
      "Tubo",
      "Villaviciosa",
    ],
  },
  {
    id: 2,
    name: "Agusan del Norte",
    cities: [
      "Buenavista",
      "Butuan",
      "Cabadbaran",
      "Carmen",
      "Jabonga",
      "Kitcharao",
      "Las Nieves",
      "Magallanes",
      "Nasipit",
      "Remedios T. Romualdez",
      "Santiago",
      "Tubay",
    ],
  },
  {
    id: 3,
    name: "Agusan del Sur",
    cities: [
      "Bayugan",
      "Bunawan",
      "Esperanza",
      "La Paz",
      "Loreto",
      "Prosperidad",
      "Rosario",
      "San Francisco",
      "San Luis",
      "Santa Josefa",
      "Sibagat",
      "Talacogon",
      "Trento",
      "Veruela",
    ],
  },
  {
    id: 4,
    name: "Aklan",
    cities: [
      "Altavas",
      "Balete",
      "Banga",
      "Batan",
      "Buruanga",
      "Ibajay",
      "Kalibo",
      "Lezo",
      "Libacao",
      "Madalag",
      "Makato",
      "Malay",
      "Malinao",
      "Nabas",
      "New Washington",
      "Numancia",
      "Tangalan",
    ],
  },
  {
    id: 5,
    name: "Albay",
    cities: [
      "Bacacay",
      "Camalig",
      "Daraga",
      "Guinobatan",
      "Jovellar",
      "Legazpi",
      "Libon",
      "Ligao",
      "Malilipot",
      "Malinao",
      "Manito",
      "Oas",
      "Pio Duran",
      "Polangui",
      "Rapu-Rapu",
      "Santo Domingo",
      "Tabaco",
      "Tiwi",
    ],
  },
  {
    id: 6,
    name: "Antique",
    cities: [
      "Anini-y",
      "Barbaza",
      "Belison",
      "Bugasong",
      "Caluya",
      "Culasi",
      "Hamtic",
      "Laua-an",
      "Libertad",
      "Pandan",
      "Patnongon",
      "San Jose de Buenavista",
      "San Remigio",
      "Sebaste",
      "Sibalom",
      "Tibiao",
      "Tobias Fornier",
      "Valderrama",
    ],
  },
  {
    id: 7,
    name: "Apayao",
    cities: [
      "Calanasan",
      "Conner",
      "Flora",
      "Kabugao",
      "Luna",
      "Pudtol",
      "Santa Marcela",
    ],
  },
  {
    id: 8,
    name: "Aurora",
    cities: [
      "Baler",
      "Casiguran",
      "Dilasag",
      "Dinalungan",
      "Dingalan",
      "Dipaculao",
      "Maria Aurora",
      "San Luis",
    ],
  },
  {
    id: 9,
    name: "Basilan",
    cities: [
      "Akbar",
      "Al-Barka",
      "Hadji Mohammad Ajul",
      "Hadji Muhtamad",
      "Isabela City",
      "Lamitan",
      "Lantawan",
      "Maluso",
      "Sumisip",
      "Tabuan-Lasa",
      "Tipo-Tipo",
      "Tuburan",
      "Ungkaya Pukan",
    ],
  },
  {
    id: 10,
    name: "Bataan",
    cities: [
      "Abucay",
      "Bagac",
      "Balanga",
      "Dinalupihan",
      "Hermosa",
      "Limay",
      "Mariveles",
      "Morong",
      "Orani",
      "Orion",
      "Pilar",
      "Samal",
    ],
  },
  {
    id: 11,
    name: "Batanes",
    cities: ["Basco", "Itbayat", "Ivana", "Mahatao", "Sabtang", "Uyugan"],
  },
  {
    id: 12,
    name: "Batangas",
    cities: [
      "Agoncillo",
      "Alitagtag",
      "Balayan",
      "Balete",
      "Batangas City",
      "Bauan",
      "Calaca",
      "Calatagan",
      "Cuenca",
      "Ibaan",
      "Laurel",
      "Lemery",
      "Lian",
      "Lipa",
      "Lobo",
      "Mabini",
      "Malvar",
      "Mataas na kahoy",
      "Nasugbu",
      "Padre Garcia",
      "Rosario",
      "San Jose",
      "San Juan",
      "San Luis",
      "San Nicolas",
      "San Pascual",
      "Santa Teresita",
      "Santo Tomas",
      "Taal",
      "Talisay",
      "Tanauan",
      "Taysan",
      "Tingloy",
      "Tuy",
    ],
  },
  {
    id: 13,
    name: "Benguet",
    cities: [
      "Atok",
      "Baguio",
      "Bakun",
      "Bokod",
      "Buguias",
      "Itogon",
      "Kabayan",
      "Kapangan",
      "Kibungan",
      "La Trinidad",
      "Mankayan",
      "Sablan",
      "Tuba",
      "Tublay",
    ],
  },
  {
    id: 14,
    name: "Biliran",
    cities: [
      "Almeria",
      "Biliran",
      "Cabucgayan",
      "Caibiran",
      "Culaba",
      "Kawayan",
      "Maripipi",
      "Naval",
    ],
  },
  {
    id: 15,
    name: "Bohol",
    cities: [
      "Alicia",
      "Anda",
      "Batuan",
      "Bilar",
      "Candijay",
      "Carmen",
      "Dimiao",
      "Duero",
      "Garcia Hernandez",
      "Guindulman",
      "Jagna",
      "Sevilla",
      "Lila",
      "Loay",
      "Loboc",
      "Mabini",
      "Pilar",
      "Sierra Bullones",
      "Valencia",
    ],
  },
  {
    id: 16,
    name: "Bukidnon",
    cities: [
      "Baungon",
      "Cabanglasan",
      "Damulog",
      "Dangcagan",
      "Don Carlos",
      "Impasugong",
      "Kadingilan",
      "Kalilangan",
      "Kibawe",
      "Kitaotao",
      "Lantapan",
      "Libona",
      "Malaybalay",
      "Malitbog",
      "Manolo Fortich",
      "Maramag",
      "Pangantucan",
      "Quezon",
      "San Fernando",
      "Sumilao",
      "Talakag",
      "Valencia",
    ],
  },
  {
    id: 17,
    name: "Bulacan",
    cities: [
      "Angat",
      "Balagtas",
      "Baliuag",
      "Bocaue",
      "Bulakan",
      "Bustos",
      "Calumpit",
      "Doña Remedios Trinidad",
      "Guiguinto",
      "Hagonoy",
      "Malolos",
      "Marilao",
      "Meycauayan",
      "Norzagaray",
      "Obando",
      "Pandi",
      "Paombong",
      "Plaridel",
      "Pulilan",
      "San Ildefonso",
      "San Jose del Monte",
      "San Miguel",
      "San Rafael",
      "Santa Maria",
    ],
  },
  {
    id: 18,
    name: "Cagayan",
    cities: [
      "Abulug",
      "Alcala",
      "Allacapan",
      "Amulung",
      "Aparri",
      "Baggao",
      "Ballesteros",
      "Buguey",
      "Calayan",
      "Camalaniugan",
      "Claveria",
      "Enrile",
      "Gattaran",
      "Gonzaga",
      "Iguig",
      "Lal-lo",
      "Lasam",
      "Pamplona",
      "Peñablanca",
      "Piat",
      "Rizal",
      "Sanchez-Mira",
      "Santa Ana",
      "Santa Praxedes",
      "Santa Teresita",
      "Santo Niño",
      "Solana",
      "Tuao",
      "Tuguegarao City",
    ],
  },
  {
    id: 19,
    name: "Camaries Norte",
    cities: [
      "Basud",
      "Capalonga",
      "Daet",
      "Jose Panganiban",
      "Labo",
      "Mercedes",
      "Paracale",
      "San Lorenzo Ruiz",
      "San Vicente",
      "Santa Elena",
      "Talisay",
      "Vinzons",
    ],
  },
  {
    id: 20,
    name: "Camarines Sur",
    cities: [
      "Baao",
      "Balatan",
      "Bato",
      "Bombon",
      "Buhi",
      "Bula",
      "Cabusao",
      "Calabanga",
      "Camaligan",
      "Canaman",
      "Caramoan",
      "Del Gallego",
      "Gainza",
      "Garchitorena",
      "Goa",
      "Iriga",
      "Lagonoy",
      "Libmanan",
      "Lupi",
      "Magarao",
      "Milaor",
      "Minalabac",
      "Nabua",
      "Naga",
      "Ocampo",
      "Pamplona",
      "Pasacao",
      "Pili",
      "Presentacion",
      "Ragay",
      "Sagñay",
      "San Fernando",
      "San Jose",
      "Sipocot",
      "Siruma",
      "Tigaon",
      "Tinambac",
    ],
  },
  {
    id: 21,
    name: "Camiguin ",
    cities: ["Catarman", "Guinsiliban", "Mahinog", "Mambajao", "Sagay"],
  },
  {
    id: 22,
    name: "Capiz",
    cities: [
      "Cuartero",
      "Dao",
      "Dumalag",
      "Dumarao",
      "Ivisan",
      "Jamindan",
      "Maayon",
      "Mambusao",
      "Panay",
      "Panitan",
      "Pilar",
      "Pontevedra",
      "President Roxas",
      "Roxas City",
      "Sapian",
      "Sigma",
      "Tapaz",
    ],
  },
  {
    id: 23,
    name: "Catanduanes",
    cities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoran",
      "Gigmoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    id: 24,
    name: "Cavite",
    cities: [
      "Alfonso",
      "Amadeo",
      "Bacoor",
      "Carmona",
      "Cavite City",
      "Dasmariñas",
      "General Emilio Aguinaldo",
      "General Mariano Alvarez",
      "General Trias",
      "Imus",
      "Indang",
      "Kawit",
      "Magallanes",
      "Maragondon",
      "Mendez",
      "Naic",
      "Noveleta",
      "Rosario",
      "Silang",
      "Tagaytay",
      "Tanza",
      "Ternate",
      "Trece Martires",
    ],
  },
  {
    id: 25,
    name: "Cebu",
    cities: [
      "Alcantara",
      "Alcoy",
      "Alegria",
      "Aloguinsan",
      "Argao",
      "Asturias",
      "Badian",
      "Balamban",
      "Bantayan",
      "Barili",
      "Bogo",
      "Boljoon",
      "Borbon",
      "Carcar",
      "Carmen",
      "Catmon",
      "Cebu City",
      "Compostela",
      "Consolacion",
      "Cordova",
      "Daanbantayan",
      "Dalaguete",
      "Danao",
      "Dumanjug",
      "Ginatilan",
      "Lapu-Lapu",
      "Liloan",
      "Madridejos",
      "Malabuyoc",
      "Mandaue",
      "Medellin",
      "Minglanilla",
      "Moalboal",
      "Naga",
      "Oslob",
      "Pilar",
      "Pinamungajan",
      "Poro",
      "Ronda",
      "Samboan",
      "San Fernando",
      "San Francisco",
      "San Remigio",
      "Santa Fe",
      "Santander",
      "Sibonga",
      "Sogod",
      "Tabogon",
      "Tabuelan",
      "Talisay",
      "Toledo",
      "Tuburan",
      "Tudela",
    ],
  },
  {
    id: 26,
    name: "Compostela valley",
    cities: [
      "Compostela",
      "Laak",
      "Mabini",
      "Maco",
      "Maragusan",
      "Mawab",
      "Monkayo",
      "Montevista",
      "Nabunturan",
      "New Bataan",
      "Pantukan",
    ],
  },
  {
    id: 27,
    name: "Cotabato",
    cities: [
      "Alamada",
      "Aleosan",
      "Antipas",
      "Arakan",
      "Banisilan",
      "Carmen",
      "Kabacan",
      "Kidapawan",
      "Libungan",
      "M'lang",
      "Magpet",
      "Makilala",
      "Matalam",
      "Midsayap",
      "Pigcawayan",
      "Pikit",
      "President Roxas",
      "Tulunan",
    ],
  },
  {
    id: 28,
    name: "Davao del Norte",
    cities: [
      "Asuncion",
      "Braulio E. Dujali",
      "Carmen",
      "Kapalong",
      "New Corella",
      "Panabo",
      "Samal",
      "San Isidro",
      "Santo Tomas",
      "Tagum",
      "Talaingod",
    ],
  },
  {
    id: 29,
    name: "Davao del Sur",
    cities: [
      "Bansalan",
      "Davao City",
      "Digos",
      "Hagonoy",
      "Kiblawan",
      "Magsaysay",
      "Malalag",
      "Matanao",
      "Padada",
      "Santa Cruz",
      "Sulop",
    ],
  },
  {
    id: 30,
    name: "Davao Oriental",
    cities: [
      "Baganga",
      "Banaybanay",
      "Boston",
      "Caraga",
      "Cateel",
      "Governor Generoso",
      "Lupon",
      "Manay",
      "Mati",
      "San Isidro",
      "Tarragona",
    ],
  },
  {
    id: 31,
    name: "Dinagat Island",
    cities: [
      "Basilisa",
      "Cagdianao",
      "Dinagat",
      "Libjo",
      "Loreto",
      "San Jose",
      "Tubajon",
    ],
  },
  {
    id: 32,
    name: "Eastern Samar",
    cities: [
      "Arteche",
      "Balangiga",
      "Balangkayan",
      "Borongan",
      "Can-avid",
      "Dolores",
      "General MacArthur",
      "Giporlos",
      "Guiuan",
      "Hernani",
      "Jipapad",
      "Lawaan",
      "Llorente",
      "Maslog",
      "Maydolong",
      "Mercedes",
      "Oras",
      "Quinapondan",
      "Salcedo",
      "San Julian",
      "San Policarpo",
      "Sulat",
      "Taft",
    ],
  },
  {
    id: 33,
    name: "Guimaras",
    cities: [
      "Buenavista",
      "Jordan",
      "Nueva Valencia",
      "San Lorenzo",
      "Sibunag",
    ],
  },
  {
    id: 34,
    name: "Ifugao",
    cities: [
      "Aguinaldo",
      "Alfonso Lista",
      "Asipulo",
      "Banaue",
      "Hingyon",
      "Hungduan",
      "Kiangan",
      "Lagawe",
      "Lamut",
      "Mayoyao",
      "Tinoc",
    ],
  },
  {
    id: 35,
    name: "Ilocos Norte",
    cities: [
      "Adams",
      "Bacarra",
      "Badoc",
      "Bangui",
      "Banna",
      "Batac",
      "Burgos",
      "Carasi",
      "Currimao",
      "Dingras",
      "Dumalneg",
      "Laoag",
      "Marcos",
      "Nueva Era",
      "Pagudpud",
      "Paoay",
      "Pasuquin",
      "Piddig",
      "Pinili",
      "San Nicolas",
      "Sarrat",
      "Solsona",
      "Vintar",
    ],
  },
  {
    id: 36,
    name: "Ilocos Sur",
    cities: [
      "Alilem",
      "Banayoyo",
      "Bantay",
      "Burgos",
      "Cabugao",
      "Candon",
      "Caoayan",
      "Cervantes",
      "Galimuyod",
      "Gregorio del Pilar",
      "Lidlidda",
      "Magsingal",
      "Nagbukel",
      "Narvacan",
      "Quirino",
      "Salcedo",
      "San Emilio",
      "San Esteban",
      "San Ildefonso",
      "San Juan",
      "San Vicente",
      "Santa",
      "Santa Catalina",
      "Santa Cruz",
      "Santa Lucia",
      "Santa Maria",
      "Santiago",
      "Santo Domingo",
      "Sigay",
      "Sinait",
      "Sugpon",
      "Suyo",
      "Tagudin",
      "Vigan",
    ],
  },
  {
    id: 37,
    name: "Iloilo",
    cities: [
      "Ajuy",
      "Alimodian",
      "Anilao",
      "Badiangan",
      "Balasan",
      "Banate",
      "Barotac Nuevo",
      "Barotac Viejo",
      "Batad",
      "Bingawan",
      "Cabatuan",
      "Calinog",
      "Carles",
      "Concepcion",
      "Dingle",
      "Dueñas",
      "Dumangas",
      "Estancia",
      "Guimbal",
      "Igbaras",
      "Iloilo City",
      "Janiuay",
      "Lambunao",
      "Leganes",
      "Lemery",
      "Leon",
      "Maasin",
      "Miagao",
      "Mina",
      "New Lucena",
      "Oton",
      "Passi",
      "Pavia",
      "Pototan",
      "San Dionisio",
      "San Enrique",
      "San Joaquin",
      "San Miguel",
      "San Rafael",
      "Santa Barbara",
      "Sara",
      "Tigbauan",
      "Tubungan",
      "Zarraga",
    ],
  },
  {
    id: 38,
    name: "Isabela",
    cities: [
      "Alicia",
      "Angadanan",
      "Aurora",
      "Benito Soliven",
      "Burgos",
      "Cabagan",
      "Cabatuan",
      "Cauayan",
      "Cordon",
      "Delfin Albano",
      "Dinapigue",
      "Divilacan",
      "Echague",
      "Gamu",
      "Ilagan",
      "Jones",
      "Luna",
      "Maconacon",
      "Mallig",
      "Naguilian",
      "Palanan",
      "Quezon",
      "Quirino",
      "Ramon",
      "Reina Mercedes",
      "Roxas",
      "San Agustin",
      "San Guillermo",
      "San Isidro",
      "San Manuel",
      "San Mariano",
      "San Mateo",
      "San Pablo",
      "Santa Maria",
      "Santiago",
      "Santo Tomas",
      "Tumauini",
    ],
  },
  {
    id: 39,
    name: "Kalinga",
    cities: [
      "Balbalan",
      "Lubuagan",
      "Pasil",
      "Pinukpuk",
      "Rizal",
      "Tabuk",
      "Tanudan",
      "Tinglayan",
    ],
  },
  {
    id: 40,
    name: "La Union",
    cities: [
      "Agoo",
      "Aringay",
      "Bacnotan",
      "Bagulin",
      "Balaoan",
      "Bangar",
      "Bauang",
      "Burgos",
      "Caba",
      "Luna",
      "Naguilian",
      "Pugo",
      "Rosario",
      "San Fernando",
      "San Gabriel",
      "San Juan",
      "Santo Tomas",
      "Santol",
      "Sudipen",
      "Tubao",
    ],
  },
  {
    id: 41,
    name: "Laguna",
    cities: [
      "Alaminos",
      "Bay",
      "Biñan",
      "Cabuyao",
      "Calamba",
      "Calauan",
      "Cavinti",
      "Famy",
      "Kalayaan",
      "Liliw",
      "Los Baños",
      "Luisiana",
      "Lumban",
      "Mabitac",
      "Magdalena",
      "Majayjay",
      "Nagcarlan",
      "Paete",
      "Pagsanjan",
      "Pakil",
      "Pangil",
      "Pila",
      "Rizal",
      "San Pablo",
      "San Pedro",
      "Santa Cruz",
      "Santa Maria",
      "Santa Rosa",
      "Siniloan",
      "Victoria",
    ],
  },
  {
    id: 42,
    name: "Lanao del Norte",
    cities: [
      "Bacolod",
      "Baloi",
      "Baroy",
      "Iligan",
      "Kapatagan",
      "Kauswagan",
      "Kolambugan",
      "Lala",
      "Linamon",
      "Magsaysay",
      "Maigo",
      "Matungao",
      "Munai",
      "Nunungan",
      "Pantao Ragat",
      "Pantar",
      "Poona Piagapo",
      "Salvador",
      "Sapad",
      "Sultan Naga Dimaporo",
      "Tagoloan",
      "Tangcal",
      "Tubod",
    ],
  },
  {
    id: 43,
    name: "Lanao del Sur",
    cities: [
      "Amai Manabilang",
      "Bacolod-Kalawi",
      "Balabagan",
      "Balindong",
      "Bayang",
      "Binidayan",
      "Buadiposo-Buntong",
      "Bubong",
      "Butig",
      "Calanogas",
      "Ditsaan-Ramain",
      "Ganassi",
      "Kapai",
      "Kapatagan",
      "Lumba-Bayabao",
      "Lumbaca-Unayan",
      "Lumbatan",
      "Lumbayanague",
      "Madalum",
      "Madamba",
      "Maguing",
      "Malabang",
      "Marantao",
      "Marawi",
      "Marogong",
      "Masiu",
      "Mulondo",
      "Pagayawan",
      "Piagapo",
      "Picong",
      "Poona Bayabao",
      "Pualas",
      "Saguiaran",
      "Sultan Dumalondong",
      "Tagoloan II",
      "Tamparan",
      "Taraka",
      "Tubaran",
      "Tugaya",
      "Wao",
    ],
  },
  {
    id: 44,
    name: "Leyte",
    cities: [
      "Abuyog",
      "Alangalang",
      "Albuera",
      "Babatngon",
      "Barugo",
      "Bato",
      "Baybay",
      "Burauen",
      "Calubian",
      "Capoocan",
      "Carigara",
      "Dagami",
      "Dulag",
      "Hilongos",
      "Hindang",
      "Inopacan",
      "Isabel",
      "Jaro",
      "Javier",
      "Julita",
      "Kananga",
      "La Paz",
      "Leyte",
      "MacArthur",
      "Mahaplag",
      "Matag-ob",
      "Matalom",
      "Mayorga",
      "Merida",
      "Ormoc",
      "Palo",
      "Palompon",
      "Pastrana",
      "San Isidro",
      "San Miguel",
      "Santa Fe",
      "Tabango",
      "Tabontabon",
      "Tacloban",
      "Tanauan",
      "Tolosa",
      "Tunga",
      "Villaba",
    ],
  },
  {
    id: 45,
    name: "Maguindanao",
    cities: [
      "Barira",
      "Buldon",
      "Datu Anggal Midtimbang",
      "Datu Blah T. Sinsuat",
      "Datu Odin Sinsuat",
      "Kabuntalan",
      "Matanog",
      "Northern Kabuntalan",
      "Parang",
      "Sultan Kudarat",
      "Sultan Mastura",
      "Sultan Sumagka",
      "Upi",
    ],
  },
  {
    id: 46,
    name: "Marinduque",
    cities: ["Boac", "Buenavista", "Gasan", "Mogpog", "Santa Cruz", "Torrijos"],
  },
  {
    id: 47,
    name: "Masbate",
    cities: [
      "Aroroy",
      "Baleno",
      "Balud",
      "Batuan",
      "Cataingan",
      "Cawayan",
      "Claveria",
      "Dimasalang",
      "Esperanza",
      "Mandaon",
      "Masbate City",
      "Milagros",
      "Mobo",
      "Monreal",
      "Palanas",
      "Pio V. Corpuz",
      "Placer",
      "San Fernando",
      "San Jacinto",
      "San Pascual",
      "Uson",
    ],
  },
  {
    id: 48,
    name: "Metro Manila",
    cities: [
      "Caloocan",
      "Las Piñas",
      "Makati",
      "Malabon",
      "Mandaluyong",
      "Manila",
      "Marikina",
      "Muntinlupa",
      "Navotas",
      "Parañaque",
      "Pasay",
      "Pasig",
      "Pateros",
      "Quezon City",
      "San Juan",
      "Taguig",
      "Valenzuela",
    ],
  },
  {
    id: 49,
    name: "Misamis Occidental",
    cities: [
      "Aloran",
      "Baliangao",
      "Bonifacio",
      "Calamba",
      "Clarin",
      "Concepcion",
      "Don Victoriano Chiongbian",
      "Jimenez",
      "Lopez Jaena",
      "Oroquieta",
      "Ozamiz",
      "Panaon",
      "Plaridel",
      "Sapang Dalaga",
      "Sinacaban",
      "Tangub",
      "Tudela",
    ],
  },
  {
    id: 50,
    name: "Misamis Oriental",
    cities: [
      "Alubijid",
      "Balingasag",
      "Balingoan",
      "Binuangan",
      "Cagayan de Oro",
      "Claveria",
      "El Salvador",
      "Gingoog",
      "Gitagum",
      "Initao",
      "Jasaan",
      "Kinoguitan",
      "Lagonglong",
      "Laguindingan",
      "Libertad",
      "Lugait",
      "Magsaysay",
      "Manticao",
      "Medina",
      "Naawan",
      "Opol",
      "Salay",
      "Sugbongcogon",
      "Tagoloan",
      "Talisayan",
      "Villanueva",
    ],
  },
  {
    id: 51,
    name: "Mountain Province",
    cities: [
      "Barlig",
      "Bauko",
      "Besao",
      "Bontoc",
      "Natonin",
      "Paracelis",
      "Sabangan",
      "Sadanga",
      "Sagada",
      "Tadian",
    ],
  },
  {
    id: 52,
    name: "Negros Occidental",
    cities: [
      "Bacolod",
      "Bago",
      "Binalbagan",
      "Cadiz",
      "Calatrava",
      "Candoni",
      "Cauayan",
      "Enrique B. Magalona",
      "Escalante",
      "Himamaylan",
      "Hinigaran",
      "Hinoba-an",
      "Ilog",
      "Isabela",
      "Kabankalan",
      "La Carlota",
      "La Castellana",
      "Manapla",
      "Moises Padilla",
      "Murcia",
      "Pontevedra",
      "Pulupandan",
      "Sagay",
      "Salvador Benedicto",
      "San Carlos",
      "San Enrique",
      "Silay",
      "Sipalay",
      "Talisay",
      "Toboso",
      "Valladolid",
      "Victorias",
    ],
  },
  {
    id: 53,
    name: "Negros Oriental",
    cities: [
      "Amlan",
      "Ayungon",
      "Bacong",
      "Bais",
      "Basay",
      "Bayawan",
      "Bindoy",
      "Canlaon",
      "Dauin",
      "Dumaguete",
      "Guihulngan",
      "Jimalalud",
      "La Libertad",
      "Mabinay",
      "Manjuyod",
      "Pamplona",
      "San Jose",
      "Santa Catalina",
      "Siaton",
      "Sibulan",
      "Tanjay",
      "Tayasan",
      "Valencia",
      "Vallehermoso",
      "Zamboanguita",
    ],
  },
  {
    id: 54,
    name: "Nothern Samar",
    cities: [
      "Allen",
      "Biri",
      "Bobon",
      "Capul",
      "Catarman",
      "Catubig",
      "Gamay",
      "Laoang",
      "Lapinig",
      "Las Navas",
      "Lavezares",
      "Lope de Vega",
      "Mapanas",
      "Mondragon",
      "Palapag",
      "Pambujan",
      "Rosario",
      "San Antonio",
      "San Isidro",
      "San Jose",
      "San Roque",
      "San Vicente",
      "Silvino Lobos",
      "Victoria",
    ],
  },
  {
    id: 55,
    name: "Nueva Ecija",
    cities: [
      "Aliaga",
      "Bongabon",
      "Cabanatuan",
      "Cabiao",
      "Carranglan",
      "Cuyapo",
      "Gabaldon",
      "Gapan",
      "General Mamerto Natividad",
      "General Tinio",
      "Guimba",
      "Jaen",
      "Laur",
      "Licab",
      "Llanera",
      "Lupao",
      "Muñoz",
      "Nampicuan",
      "Palayan",
      "Pantabangan",
      "Peñaranda",
      "Quezon",
      "Rizal",
      "San Antonio",
      "San Isidro",
      "Cabaritan",
      "San Leonardo",
      "Santa Rosa",
      "Santo Domingo",
      "Talavera",
      "Talugtug",
      "Zaragoza",
    ],
  },
  {
    id: 56,
    name: "Nueva Vizcaya",
    cities: [
      "Alfonso Castañeda",
      "Ambaguio",
      "Aritao",
      "Bagabag",
      "Bambang",
      "Bayombong",
      "Diadi",
      "Dupax del Norte",
      "Dupax del Sur",
      "Kasibu",
      "Kayapa",
      "Quezon",
      "Santa Fe",
      "Solano",
      "Villaverde",
    ],
  },
  {
    id: 57,
    name: "Occidental Mindoro",
    cities: [
      "Abra de Ilog",
      "Calintaan",
      "Looc",
      "Lubang",
      "Magsaysay",
      "Mamburao",
      "Paluan",
      "Rizal",
      "Sablayan",
      "San Jose",
      "Santa Cruz",
    ],
  },
  {
    id: 58,
    name: "Oriental Mindoro",
    cities: [
      "Baco",
      "Bansud",
      "Bongabong",
      "Bulalacao",
      "Calapan",
      "Gloria",
      "Mansalay",
      "Naujan",
      "Pinamalayan",
      "Pola",
      "Puerto Galera",
      "Roxas",
      "San Teodoro",
      "Socorro",
      "Victoria",
    ],
  },
  {
    id: 59,
    name: "Palawan",
    cities: [
      "Aborlan",
      "Agutaya",
      "Araceli",
      "Balabac",
      "Bataraza",
      "Brooke's Point",
      "Busuanga",
      "Cagayancillo",
      "Coron",
      "Culion",
      "Cuyo",
      "Dumaran",
      "El Nido",
      "Kalayaan",
      "Linapacan",
      "Magsaysay",
      "Narra",
      "Puerto Princesa",
      "Quezon",
      "Rizal",
      "Roxas",
      "San Vicente",
      "Sofronio Española",
      "Taytay",
    ],
  },
];

export function getCities() {
  return city;
}

export function getCity(province) {
  return city.find((m) => m.name === province);
}
